### ISSUE TITLE
Tracking: Unflagging exports in node.js

### ISSUE THREAD

**Issue by hybrist** [jkrems/proposal-pkg-exports#36]
#### Land Flagged Implementation

~~WIP PR: https://github.com/nodejs/ecmascript-modules/pull/72~~

- [x] Respond and implement Jordans comments re handling "exports": null cases etc.
- [x] Remove dot main support.
- [x] [Make Core PR](https://github.com/nodejs/node/pull/28568).

#### Follow-up Work

- [ ] Consider key / target validations (if any?).
- [ ] [CommonJS implementation](https://github.com/nodejs/node/pull/28759).
- [ ] Make call on support for differential exports.
- [ ] Make call on support for package-internal entries.
- [ ] Plug the hole on windows where `x\\foo.js` can get to `foo.js` even if it isn't exported.
- [ ] Normalize `exports` mappings in CJS so that URL paths turn into valid file paths.

**Comment by hybrist** [comment]
Replaced with project: https://github.com/orgs/nodejs/projects/3
